### PR TITLE
Added support for apostrophe as thousand separator.

### PR DESCRIPTION
**Pull request by acautin**

### CODE REVIEW

**Comment by uhlryk** [comment]
Hi
Thank you very much for your effort. Unfortunately there are some errors (I didn't identify their source yet).
I created new branch with your commit and add there additional commit with tests for apostrophe. Also I updated examples, there is one example with apostrophe. You can pull this branch https://github.com/uhlryk/angular-dynamic-number/tree/apostrophe_thousand_separator or only check my tests - maybe I made mistake with it. In examples it is 5th input - write 99999999 number - it will stop on 9'999 and it also shows model value 9'999, but model value should be 9999. Also if you try delete last values by backspace it doesn't work too.

I will be very happy if you success to fix it.
Otherwise I will try it myself at weekend.

**Comment by uhlryk** [comment]
To run tests type in cli `gulp tests`

**Comment by acautin** [comment]
@uhlryk should be fixed now, I was not removing the apostrophe from the model properly and as I only need the filter I didn't notice 😄

**Comment by uhlryk** [comment]
@acautin thank you for your work. Everything is merged in latest version 1.11.0

**Comment by acautin** [comment]
@uhlryk thank you very much for the prompt reply 👍

**Pull request merged**
